name: Generate Snake

# Controls when the action will run. This action runs every 6 hours.
on:
  schedule:
    # every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:  # Allows manual runs from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest  # Specify the runner

    steps:
      # Check out the repository
      - uses: actions/checkout@v3

      # Generate the snake contribution graph
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.gif
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Display git status for debugging purposes
      - name: Show build status
        run: git status

      # Push new files to the output branch
      - name: Push new files to output branch 
        uses: crazy-max/ghaction-github-pages@v4  # Update to a newer version for Node 20 compatibility
        with:
          target_branch: output  # Output branch to store generated files
          build_dir: dist
          commit_message: Update snake animations
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
